server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: analyzer
          uri: lb://analizer
          predicates:
            - Path=/analizer/**
        - id: parser
          uri: lb://parser
          predicates:
            - Path=/parser/**
        - id: telegrambot
          uri: lb://telegrambot
          predicates:
            - Path=/telegrambot/**

